name: Generate changelog and publish pacakge to pypi

on:
  push:
    tags:
      - '*'

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    outputs:
      old-version: ${{ steps.step-version-bump.outputs.OLD_VERSION }}
      new-version: ${{ steps.step-version-bump.outputs.NEW_VERSION }}
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate Changelog
        run: |
          python -m pip install --upgrade pip
          pip install towncrier
          # will remove files from changelog.d/ and update changelog.md file
          towncrier build --version ${{ github.ref_name }} --yes

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "changelog for ${{ github.ref_name }}" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  publish-to-pypi:
    name: Publish to Pypi
    needs: [ "generate-changelog" ]
    uses: papermerge/papermerge-core/.github/workflows/publish-to-pypi.yml@master
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
